name: PR

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_call:
    inputs:
      config-path:
        required: false
        type: string

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run --prefix packages/core build
    - run: |
        npm run --prefix packages/core test
        npm run --prefix packages/core coverage
    - run: |
        npm run --prefix packages/react test
        npm run --prefix packages/react coverage
    - name: Coveralls:core
      uses: coverallsapp/github-action@master
      with:
        base-path: packages/core
        path-to-lcov: "./packages/core/coverage/lcov.info"
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Coveralls:react
      uses: coverallsapp/github-action@master
      with:
        base-path: packages/react
        path-to-lcov: "./packages/react/coverage/lcov.info"
        github-token: ${{ secrets.GITHUB_TOKEN }}
